### ISSUE TITLE
Transitive dependency causes compile error

### ISSUE THREAD

**Issue by wanderrful** [TanTanDev/flappy_bevy#3]
A dependency called `notify` doesn't exist anymore in `bevy_asset`, but it did at the time when you made this and so when I tried to run this project, Cargo installs `notify:5.0.0-pre.13` instead of what it should have been, which is `5.0.0-pre.2`.  

Unfortunately, the people working on that project made a breaking change without bumping the minor version or whatever (probably because it's a "pre" thing and so it's not stable), but Cargo doesn't understand that and so it just grabs the latest thing instead of the one it's supposed to grab.

This `Watcher::new_immediate` method doesn't exist anymore in that `notify` dependency... and so it causes this project to crash when you try to run/compile it.

**Comment by TanTanDev** [comment]
Thanks a lot!
Also thanks for explaining it so thoroughly
